### ISSUE TITLE
Ready to make public and release?

### ISSUE THREAD

**Issue by dhimmel** [related-sciences/nxontology#1]
I based a lot of the infrastructure on [ravwojdyla/pyspark_gcs](https://github.com/ravwojdyla/pyspark_gcs/tree/44e0c53d0a463ad558e4e3784b60cf4f46b8a055).

Currently the code doesn't have the version number anywhere in it (same as pyspark_gcs). That does make it slightly less of a hassle to make new releases. I was planning on setting up GitHub actions for PyPI deployment upon release.

@ravwojdyla did you want to check things over to see if the package looks good to you?

Repo is not public yet.

**Comment by dhimmel** [comment]
Closing as now released and public, but feel free to continue discussion.

**Comment by dhimmel** [comment]
> setup long_description

I think using the following lines in setup.cfg will actually allow us to use the README for the long_description in a declarative way:

```ini
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
```

**Comment by ravwojdyla** [comment]
@dhimmel good to see that setup won't have that extra custom logic regarding readme.

> If we think there's a need to install dev requirements via conda, perhaps we can switch to a requirements-dev.txt, but for now I was just using venv locally since the dependencies are light.

That plus you can't install the dev dependencies without installing the package itself.
