### ISSUE TITLE
Should nxontology graphs contain additional relationships beyond subClassOf / is_a relations?

### ISSUE THREAD

**Issue by jsanjak** [related-sciences/nxontology#14]
I have an interest in obtaining a graph where I can choose to represent both subClassOf / is_a and other relations. For example, in the gene ontology I want to include the part_of, regulates, etc... relationships in my graph. Is there any interest in making this an option in imports.from_file? If so, I would be willing to make a first pass at a pr. If not, no worries, I will just make my own local solution using pronto directly in my project. 

P.S. I realize this isn't really an "issue" but I don't see a discussion forum.

**Comment by dhimmel** [comment]
https://github.com/related-sciences/nxontology/pull/15 includes a `nxontology.imports.read_gene_ontology` function that loads the relationship types from GO Basic:

> This is the basic version of the GO, filtered such that the graph is guaranteed to be acyclic and annotations can be propagated up the graph. The relations included are is a, part of, regulates, negatively regulates and positively regulates. This version excludes relationships that cross the 3 GO hierarchies. This version should be used with most GO-based annotation tools.

**Comment by dhimmel** [comment]
New functions will be included in the [v0.3.1](https://github.com/related-sciences/nxontology/releases/tag/v0.3.1) release including `read_gene_ontology` and `pronto_to_multidigraph`.

**Comment by cthoyt** [comment]
Surprising that people are still able to find onto2nx!
