### ISSUE TITLE
Subsetting an ontology

### ISSUE THREAD

**Issue by kenbabu** [related-sciences/nxontology#17]
Is there a way to subset an ontology by namespace. For example  for the gene ontology (GO) if I'm only interested in the biological process namespace. Is there a way of creating a subontology that only has biological process terms?

**Comment by dhimmel** [comment]
This will get you all a subgraph with descendants of `GO:0008150` (biological process):

```py
from nxontology.imports import read_gene_ontology
from nxontology import NXOntology
go_nxo = read_gene_ontology(release="2021-02-01")
bp = go_nxo.node_info("GO:0008150")  # biological process
go_bp = NXOntology(go_nxo.graph.subgraph(bp.descendants))
print(go_nxo.n_nodes, go_bp.n_nodes)
```

Reduces from 44085 nodes to 28748.

But I noticed when doing this that node metadata is missing from go_nxo, so the method I wanted to use, which was filter for namespace, is not available. Will look into this.

**Comment by dhimmel** [comment]
> But I noticed when doing this that node metadata is missing from go_nxo

will be fixed by https://github.com/related-sciences/nxontology/pull/18

**Comment by dhimmel** [comment]
Here's the second method I wanted to show you that uses the `namespace` node attribute rather than descendants of the biological process root node:

```py
bp_nodes = {node for node, data in go_nxo.graph.nodes(data=True) if data["namespace"] == "biological_process"}
go_bp = NXOntology(go_nxo.graph.subgraph(bp_nodes))
```

They are the same because the each GO domain/namespace is disconnected from the other domains. If there were cross-domain connections, then only this namespace method would work.

**Comment by kenbabu** [comment]
Thanks! I was actually thinking of the first method but I wasn't sure that it would work if I wanted to retrieve ancestors of terms from the subset graph. For some reason I thought that ancestors that are derived from terms in the subgraph may still contain  those that are derived from other relations such as 'part of' and those that are present in MF and CC  given that the ontology object is created from a multi-graph. The main reason why I'm going through nxontology is that I wanted to add the GO Universal semantic similarity calculation method that is described in this paper https://www.researchgate.net/publication/225187134_A_Topology-Based_Metric_for_Measuring_Term_Similarity_in_the_Gene_Ontology. It uses a different method for calculating IC than the Resnik method which is prominent in the methods that you've already implemented.
