### ISSUE TITLE
Error while parsing OBO ontologies and quoted strings

### ISSUE THREAD

**Issue by Zerskk** [related-sciences/nxontology#23]
Some OBO ontologies contain additional information after the quotation marks. 
Examples of this can be found in the def and xref tags.
This seems to be correct according to:
https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html.

Examples can be found in this ontology:
https://raw.githubusercontent.com/EnvironmentOntology/envo/master/envo.obo

Error while parsing with nxontology:
```
  File ".../lib/python3.10/site-packages/pronto/parsers/obo.py", line 45, in parse_from
    raise SyntaxError(s.args[0], location) from None
File "/ontologies/envo.obo", line 22109
    def: "A mass of salt which has erupted onto a planetary surface, usually through sedimentary rock." [Adapted from URL:http\://earthobservatory.nasa.gov/IOTD/view.php?id=86861]␊

SyntaxError: expected QuotedString
```

Term at which the Parser fails:

```
[Term]
id: ENVO:01000450
name: salt glacier
def: "A mass of salt which has erupted onto a planetary surface, usually through sedimentary rock." [Adapted from URL:http\://earthobservatory.nasa.gov/IOTD/view.php?id=86861]
```

**Comment by dhimmel** [comment]
Okay here's a versioned link to [`envo.obo`](https://github.com/EnvironmentOntology/envo/blob/d3b59a2cead7ab204c2850e121c9dcacf99c2bfc/envo.obo) for posterity.

This looks like a fastobo issue, which is an upstream dependency of nxontology:

```py
import io
import requests
import fastobo

url = "https://github.com/EnvironmentOntology/envo/raw/d3b59a2cead7ab204c2850e121c9dcacf99c2bfc/envo.obo"
response = requests.get(url)
fastobo.load(io.BytesIO(response.content))
```

Produces the same error (fastobo v0.11.1):

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 22109
    def: "A mass of salt which has erupted onto a planetary surface, usually through sedimentary rock." [Adapted from URL:http\://earthobservatory.nasa.gov/IOTD/view.php?id=86861]␊
                                                                                                                 ^
SyntaxError: expected QuotedString
```

Probably best to report this at https://github.com/fastobo/fastobo/issues and link to this issue for context?

**Comment by dhimmel** [comment]
> Examples of this can be found in the def and xref tags.

Noting the examples in the 1.4 obo spec:

> The brackets may contain zero or more comma separated dbxref definitions. An example of a dbxref list can be seen in the GO def for "ribonuclease MRP complex":
>
> ```
> def: "A ribonucleoprotein complex that contains an RNA molecule of the snoRNA family, and cleaves the rRNA precursor as part of rRNA transcript processing. It also has other roles: In S. cerevisiae it is involved in cell cycle-regulated degradation of daughter cell-specific mRNAs, while in mammalian cells it also enters the mitochondria and processes RNAs to create RNA primers for DNA replication." [GOC:sgd_curators, PMID:10690410, PMID:14729943, PMID:7510714]
> ```

I think this format is the "Trailing Modifiers" with this documentation:

> Any tag-value pair may be followed by a trailing modifier. Trailing modifiers have been introduced into the OBO 1.2 Specification to allow the graceful addition of new features to existing tags.
> 
> A trailing modifier has the following structure:
> 
> `{<name>=<value>, <name=value>, <name=value>}`
> 
> That is, trailing modifiers are lists of name-value pairs.
> 
> Parser implementations may choose to decode and/or round-trip these trailing modifiers. However, this is not required. A parser may choose to ignore or strip away trailing modifiers.
> 
> For this reason, trailing modifiers should only include information that is optional or experimental.
> 
> Trailing modifiers may also occur within dbxref definitions (see [dbxref formatting](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2.3)).

Seems like `[Adapted from URL:http\://earthobservatory.nasa.gov/IOTD/view.php?id=86861]` might be an invalid trailing modifier, so this also could be an EnvironmentOntology issue.

**Comment by dhimmel** [comment]
closing issue since it's an upstream problem, but encourage this to be reported to the relevant repos.

CC @althonos in case this issue is of interest to fastobo.
CC @pbuttigieg from [The Environment Ontology](https://github.com/EnvironmentOntology/envo)

**Comment by althonos** [comment]
As @dhimmel pointed out this part should be a cross reference in OBO 1.4, so it should only contain an URI or an URI with a quoted description.

**Comment by dhimmel** [comment]
@pbuttigieg @wdduncan: I can submit a PR to fix this to https://github.com/EnvironmentOntology/envo, but not sure which of the files is the source [from these](https://github.com/search?q=repo%3AEnvironmentOntology%2Fenvo+%22ENVO%3A01000450%22&type=code)? I.e. which file does the change need to be made in to propagate to the rest of the files?

**Comment by althonos** [comment]
@dhimmel : Unfortunately I can't do that because the parser uses a grammar, not line-based decoding, so I can't choose to strip arbitrary parts of the offending lines.

**Comment by dhimmel** [comment]
> Unfortunately I can't do that because the parser uses a grammar, not line-based decoding

Good to know. But in that case, would be possible to drop the line entirely as presumably the ontology is still largely intact with just a missing defintion?

**Comment by althonos** [comment]
The only thing I could do is to drop an entire frame, not just a line :disappointed:
