### ISSUE TITLE
can not install nxontology package

### ISSUE THREAD

**Issue by 22842219** [related-sciences/nxontology#8]
Hi, I've got a package installation error. Could you please help to answer my question? Thanks.

My execute command line : "!pip install nxontology" in jupyter notebook. 
Error report :

```
ERROR: Could not find a version that satisfies the requirement nxontology
ERROR: No matching distribution found for nxontology
```

**Comment by dhimmel** [comment]
Sorry I missed this. Somehow I wasn't watching this repo.

Not sure why you are getting this error. Perhaps your version of pip is out of date. You could try running `pip install --upgrade pip`. And you are using Python 3 right?

**Comment by 22842219** [comment]
> Sorry I missed this. Somehow I wasn't watching this repo.
> 
> Not sure why you are getting this error. Perhaps your version of pip is out of date. You could try running `pip install --upgrade pip`.
> 
> What version of Python are you using? The package requires Python 3.7+
> 
> https://github.com/related-sciences/nxontology/blob/970ee9a773b9bf907bb47afc705d40c8f0df5014/setup.cfg#L30
> 
> Would have like a better error message!

Hi, thanks for replying me. Yes, I'm using python3  and My ubuntu has installed python3.9 as well. But somehow I still cannot install nxontology and I've got same error. Any idea and suggestion? Thanks.

**Comment by dhimmel** [comment]
Hmm I'm using a Ubuntu linux distro as well with Python 3.8.6 and can't replicate this. What if you try `pip3 install nxontology`? Or `python3 -m pip install nxontology`?

**Comment by dhimmel** [comment]
I am going to close this issue because it sounds like a more general issue than something that is misconfigured with nxontology. But feel free to continuing posting updates. And if anyone else gets this issue, let us know!
